### ISSUE TITLE
openAPK keeps stopping

### ISSUE THREAD

**Issue by diehard88** [dkanada/OpenAPK#30]
Crashes when I click the 'play store' icon of any app.
![](https://i.imgur.com/8detmFb.jpg)

```
-------- beginning of crash
07-01 00:01:00.876 17815 17815 E AndroidRuntime: FATAL EXCEPTION: main
07-01 00:01:00.876 17815 17815 E AndroidRuntime: Process: com.dkanada.openapk, PID: 17815
07-01 00:01:00.876 17815 17815 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Download/apkbkp/com.istomgames.cars.apk exposed beyond app through ClipData.Item.getUri()
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2356)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:944)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10480)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10486)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10465)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4564)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4522)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4883)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4851)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at com.dkanada.openapk.utils.ActionUtils.share(ActionUtils.java:63)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at com.dkanada.openapk.activities.AppActivity$5.onClick(AppActivity.java:134)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.view.View.performClick(View.java:6897)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26101)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6949)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-01 00:01:00.876 17815 17815 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-01 00:01:00.882  1509  3181 D Debug   : !@DumpState : SHIP
07-01 00:01:00.883  1509  3181 D Debug   : !@DumpState : debug level:0x4f4c
07-01 00:01:00.883  1509  3181 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
07-01 00:01:00.884  1509  3181 W ActivityManager: crash : com.dkanada.openapk,0
07-01 00:01:00.889  1509  3181 W ActivityManager:   Force finishing activity com.dkanada.openapk/.activities.AppActivity
07-01 00:01:00.902  1509  1590 I ActivityManager: Showing crash dialog for package com.dkanada.openapk u0
07-01 00:01:00.909 17425 17425 I DMT-SMReceiver: Received : com.samsung.android.sm.ACTION_ERROR
07-01 00:01:00.914  1509  1590 D ScrollView: initGoToTop
07-01 00:01:00.925 17425 17425 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1483 android.content.ContextWrapper.startService:663 android.content.ContextWrapper.startService:663 com.samsung.android.sm.common.SmartManagerReceiver.a:211 com.samsung.android.sm.common.SmartManagerReceiver.onReceive:94 
07-01 00:01:00.942  1509  1590 D RestrictionPolicy: isGoogleCrashReportAllowed : ret=true userId =0
07-01 00:01:00.946  1509  1590 E PhoneWindow_APM : : isCalledPackage return false
07-01 00:01:00.947  1509  1594 V MARsPolicyManager: handelAlertToastWindowStarted pkgName = android, userId = 0
07-01 00:01:00.949  1509  1590 D InputDispatcher: Focus left window: 17815
07-01 00:01:00.949  1509  1590 D InputDispatcher: Focus entered window: 1509
07-01 00:01:00.950
```

**Comment by diehard88** [comment]
this happening on a samsung tab s3 (sm-t820) running oreo.

**Comment by dkanada** [comment]
Huh that explains the issue on my phone as well. Here is a [fix](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed#38858040) for the issue, I will implement it if I ever have some time. Right now the project is in limbo because I started a rewrite and then decided I hated the rewrite, so now to release a new version I would have to rip out all the sections of the rewrite I don't like and that would take ages.

**Comment by diehard88** [comment]
Merci...

**Comment by sebma** [comment]
I have the same pb. on my BV9500Pro, it's related to [issue#20](../issues/20)

**Comment by sebma** [comment]
@dkanada Hi, did you get some time to fix this issue ?
